# Tratamento de Exceções

## Definição
Ao invés de deixarmos o programa finalizar por causa de situações inesperadas, podemos escrever código para resolver essas exceções e continuar a execução do programa. Essa é a principal funcionalidade a ferramenta ```try catch``` no Java.

## Exceções comuns

### Divisão por zero

```java
class DivisaoPorZero {
  public static void main(String[] args){
    Int x = 100;
    Int y = 0;
    try {
        System.out.println(x / y); 
    }
    catch (ArithmeticException e) {
        System.out.println("Não existe divisão por Zero");
    }
  }
}
```

### Conversão de tipos de dados inválidos

```java
public static void main(String[] args){
  String x = "abc"
  Int y = 100
  try {
    System.out.println(x / y); 
  }
  catch (IllegalArgumentException e) {
    System.out.println("Não é possível dividir uma string por um inteiro");
  }
}
```

### Acessar uma posição inválida em um arranjo

```java
public class main{
  public static void main(String[] args) {
    try {
      ArrayList arl = new ArrayList<>();
      lrl.get(99)
    } catch (IndexOutOfBoundsException  e) {
      System.out.print("Posição não encontrada");
    }
  }
}
```

### Acessar uma String nula

```java
public class main{
  public static void main(String[] args) {
    try {
      String str = null;
      str.endsWith("test");
    } catch (NullPointerException e) { // Ocorre quando há uma tentativa de acessar algum objeto que seja “null”
      System.out.print("Objeto não iniciado ou com valor nulo");
    }
  }
}
```

## Bloco para capturar uma exceção

```java
  try {
    comando(s);
  } catch (ClasseDeException VarException) { // Capturar uma exceção
    comando(s);
  } 
```

## Bloco para capturar diferentes exceções

```java
  try {
    comando(s);
  } catch (ClasseDeException VarException) { // Capturar várias exceções
    comando(s);
  } catch (ClasseDeException VarException) { // Capturar várias exceções
    comando(s);
  }
```

## Bloco finally

```java
  try {
    comando(s);
  } catch (ClasseDeException VarException) {
    comando(s);
  } finally { // Os comandos dentro de um bloco finally serão executados de qualquer maneira, mesmo que a execução tenha passado por um bloco catch.
    comando(s);
  }
```

## Lançar uma exceção

```java
public class ExemploThrow {
  public static void main(String[] args) {
    try {
      Scanner scn = new Scanner(System.in);
      System.out.print("Digite a senha: ");
      String senha = scn.nextLine();
      if(!senha.equals(" ")) {
        throw new Exception("Senha invalida!!!"); // Lança um exceção
      }
      System.out.println("Senha cadastrada com sucesso !");
    } catch (Exception ex) {
      System.out.println(ex.getMessage());
    }
  }
}
```